xgboost_proc_type:
# - cpu
  - gpu
cuda_compiler:
  - nvcc
c_compiler:
  - gcc                        # [linux]
c_compiler_version:            # [unix]
  - 11                         # [linux64 or aarch64]
cxx_compiler:
  - gxx                        # [linux]
cxx_compiler_version:          # [unix]
  - 11                         # [linux64 or aarch64]
