xgboost_proc_type:
# - cpu
  - gpu
cuda_compiler:
  - nvcc
cuda_compiler_version:
  - 11.5
c_compiler:
  - gcc                        # [linux]
c_compiler_version:            # [unix]
  - 7                          # [linux64 or aarch64]
cxx_compiler:
  - gxx                        # [linux]
cxx_compiler_version:          # [unix]
  - 7                          # [linux64 or aarch64]
